### ISSUE TITLE
Identifikuj reusabe komponenty na stranke

### ISSUE THREAD

**Issue by vmasek** [panSteven4/clarina#3]
Vytvor list kde bude komponent a k nemu screenshoty vsetkych stavov ktore moze nadobudnut

**Comment by panSteven4** [comment]
Reusable komponenty:
- product container, product
- product filter
- navbar, head (the part with logo, login, cart, language-dropdown,..)
- footer (contact, random info, license)
- katalog instrument photo grid ([e.g.](https://www.clarina.cz/smyccove-nastroje/) clarina/smyccove-nastroje (the thing above filter))
- path memory bar ([e.g.](https://www.clarina.cz/smyccove-nastroje/) the brown thing below red navbar)
